[package]
name = "xorfilter-rs"
version = "0.2.0"
authors = ["prataprc <prataprc@gmail.com>"]
edition = "2018"
description = "Xor Filters: Faster and Smaller Than Bloom and Cuckoo Filters"
license = "Apache-2.0"
documentation = "https://docs.rs/xorfilter-rs"
homepage = "https://github.com/bnclabs/xorfilter"
repository = "https://github.com/bnclabs/xorfilter"

[lib]
name = "xorfilter"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
rand = "0.6.4"
criterion = "0.3"

[[bench]]
name = "xor_bench"
harness = false
